# This workflow will build the extension and upload an artifact
name: Build and upload extension

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends make gettext gnome-shell libglib2.0-bin

    - name: Build the extension bundle
      run: |
        make build

    - name: Run checks on extension
      run: |
        make check

    - uses: actions/upload-artifact@v3
      with:
        name: PrivacyMenu@stuarthayhurst.shell-extension.zip
        path: build/PrivacyMenu@stuarthayhurst.shell-extension.zip

    - name: Upload extension bundle to release
      uses: actions/github-script@v6
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        script: |
            const fs = require('fs');
            const tag = context.ref.replace('refs/tags/', '');
            //Get release for this tag
            const release = await github.rest.repos.getReleaseByTag({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              tag
            });
            //Upload
            const bundleName = 'PrivacyMenu@stuarthayhurst.shell-extension.zip';
            await github.rest.repos.uploadReleaseAsset({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              release_id: release.data.id,
              name: bundleName,
              data: await fs.readFileSync('build/' + bundleName)
            });
